version: '3'
services:
    postegresql:
        image: postgres
        restart: always
        ports:
            - "5432:5432"
        build:
            context: .
            dockerfile: Dockerfile
        environment:
          POSTGRES_USER: ${POSTGRES_USER}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
          POSTGRES_DB: ${POSTGRES_DB}
          POSTGRES_SSL_KEY: ${POSTGRES_SSL_KEY}
          POSTGRES_SSL_SRT: ${POSTGRES_SSL_SRT}
        volumes:
          - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: